"""septima migración

Revision ID: 0abc16d8f6a3
Revises: c9276b548134
Create Date: 2025-08-15 13:38:25.635344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0abc16d8f6a3'
down_revision: Union[str, Sequence[str], None] = 'c9276b548134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('edition', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('sale', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('edition', 'created_at')
    op.drop_column('customer', 'created_at')
    # ### end Alembic commands ###
