"""Add edition status enum

Revision ID: 1255d81fbc28
Revises: bee0441ad751
Create Date: 2025-08-18 16:56:13.258386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1255d81fbc28'
down_revision: Union[str, Sequence[str], None] = 'bee0441ad751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edition', sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FINISHED', 'CANCELLED', name='editionstatus'), server_default=sa.text("'PENDING'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edition', 'status')
    # ### end Alembic commands ###
