"""new db tables ingredient/purchase/edition-ingredient

Revision ID: 171cb7a7d0da
Revises: 16f84615963b
Create Date: 2025-08-17 12:34:24.943052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '171cb7a7d0da'
down_revision: Union[str, Sequence[str], None] = '16f84615963b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('MEAT', 'SAUSAGES', 'LEGUMES', 'VEGETABLES', 'STORE', 'DISPOSABLE', name='category'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_name'), 'ingredient', ['name'], unique=True)
    op.create_table('edition_ingredient',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('edition_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'ingredient_id', name='uq_edition_ingredient')
    )
    op.create_index(op.f('ix_edition_ingredient_edition_id'), 'edition_ingredient', ['edition_id'], unique=False)
    op.create_index(op.f('ix_edition_ingredient_id'), 'edition_ingredient', ['id'], unique=False)
    op.create_index(op.f('ix_edition_ingredient_ingredient_id'), 'edition_ingredient', ['ingredient_id'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_id'), 'purchase', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_ingredient_id'), 'purchase', ['ingredient_id'], unique=False)
    op.alter_column('edition', 'portion_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sale', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sale', 'payment_status',
               existing_type=postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'FAILED', name='paymentstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'payment_status',
               existing_type=postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'FAILED', name='paymentstatus'),
               nullable=True)
    op.alter_column('sale', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('edition', 'portion_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_purchase_ingredient_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_id'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_edition_ingredient_ingredient_id'), table_name='edition_ingredient')
    op.drop_index(op.f('ix_edition_ingredient_id'), table_name='edition_ingredient')
    op.drop_index(op.f('ix_edition_ingredient_edition_id'), table_name='edition_ingredient')
    op.drop_table('edition_ingredient')
    op.drop_index(op.f('ix_ingredient_name'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
