"""Add 'other' value for category enum

Revision ID: 3f0bab01a867
Revises: 171cb7a7d0da
Create Date: 2025-08-17 15:56:24.970472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0bab01a867'
down_revision: Union[str, Sequence[str], None] = '171cb7a7d0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE category ADD VALUE 'OTHER';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
