"""Add freeze and dalivery flags

Revision ID: 4098f9ad04f5
Revises: 1255d81fbc28
Create Date: 2025-08-18 19:30:49.621190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4098f9ad04f5'
down_revision: Union[str, Sequence[str], None] = '1255d81fbc28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('freeze', sa.Boolean(), nullable=True))
    op.add_column('sale', sa.Column('delivery', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale', 'delivery')
    op.drop_column('sale', 'freeze')
    # ### end Alembic commands ###
