"""Add Payment status and create purchase

Revision ID: 41f446c8e25d
Revises: 3f0bab01a867
Create Date: 2025-08-17 23:56:55.591407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f446c8e25d'
down_revision: Union[str, Sequence[str], None] = '3f0bab01a867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edition_ingredient', sa.Column('purchase_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_edition_ingredient_purchase_id'), 'edition_ingredient', ['purchase_id'], unique=False)
    op.create_foreign_key(None, 'edition_ingredient', 'purchase', ['purchase_id'], ['id'], ondelete='SET NULL')
    op.add_column('purchase', sa.Column('edition_id', sa.BigInteger(), nullable=True))
    op.add_column('purchase', sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'FAILED', name='payment_status', native_enum=False), nullable=False))
    op.create_index(op.f('ix_purchase_edition_id'), 'purchase', ['edition_id'], unique=False)
    op.create_index('ix_purchase_ingredient_paymentstatus', 'purchase', ['ingredient_id', 'payment_status'], unique=False)
    op.create_foreign_key(None, 'purchase', 'edition', ['edition_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_index('ix_purchase_ingredient_paymentstatus', table_name='purchase')
    op.drop_index(op.f('ix_purchase_edition_id'), table_name='purchase')
    op.drop_column('purchase', 'payment_status')
    op.drop_column('purchase', 'edition_id')
    op.drop_constraint(None, 'edition_ingredient', type_='foreignkey')
    op.drop_index(op.f('ix_edition_ingredient_purchase_id'), table_name='edition_ingredient')
    op.drop_column('edition_ingredient', 'purchase_id')
    # ### end Alembic commands ###
