"""Add uq sale edition customer

Revision ID: 870f9b949df2
Revises: 4098f9ad04f5
Create Date: 2025-08-19 00:23:59.466847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870f9b949df2'
down_revision: Union[str, Sequence[str], None] = '4098f9ad04f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sale_edition_customer', 'sale', ['edition_id', 'customer_id'])
    op.drop_constraint(op.f('sale_customer_id_fkey'), 'sale', type_='foreignkey')
    op.drop_constraint(op.f('sale_edition_id_fkey'), 'sale', type_='foreignkey')
    op.create_foreign_key(None, 'sale', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sale', 'edition', ['edition_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.create_foreign_key(op.f('sale_edition_id_fkey'), 'sale', 'edition', ['edition_id'], ['id'])
    op.create_foreign_key(op.f('sale_customer_id_fkey'), 'sale', 'customer', ['customer_id'], ['id'])
    op.drop_constraint('uq_sale_edition_customer', 'sale', type_='unique')
    # ### end Alembic commands ###
