"""octava migración

Revision ID: 8c09c0b4901b
Revises: 0abc16d8f6a3
Create Date: 2025-08-15 13:47:01.790165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c09c0b4901b'
down_revision: Union[str, Sequence[str], None] = '0abc16d8f6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_index('ix_sale_customer_edition', 'sale', ['customer_id', 'edition_id'], unique=False)
    op.create_index(op.f('ix_sale_customer_id'), 'sale', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sale_edition_id'), 'sale', ['edition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_edition_id'), table_name='sale')
    op.drop_index(op.f('ix_sale_customer_id'), table_name='sale')
    op.drop_index('ix_sale_customer_edition', table_name='sale')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    # ### end Alembic commands ###
