"""cuarta migración

Revision ID: a63e62a93077
Revises: 24600f754977
Create Date: 2025-08-15 12:32:00.422237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63e62a93077'
down_revision: Union[str, Sequence[str], None] = '24600f754977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('total_amount', sa.Numeric(), nullable=False),
    sa.Column('total_portions', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('payment_transfer', sa.Boolean(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('additional_cost', sa.Numeric(), nullable=True),
    sa.Column('sold_by', sa.BigInteger(), nullable=True),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('discount_price', sa.Numeric(), nullable=True),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('edition_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['edition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_id'), 'sale', ['id'], unique=False)
    op.add_column('edition', sa.Column('portion_price', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edition', 'portion_price')
    op.drop_index(op.f('ix_sale_id'), table_name='sale')
    op.drop_table('sale')
    # ### end Alembic commands ###
