"""novena migración

Revision ID: e625f8782089
Revises: 8c09c0b4901b
Create Date: 2025-08-15 14:28:49.705572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e625f8782089'
down_revision: Union[str, Sequence[str], None] = '8c09c0b4901b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'payment_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'FAILED', name='paymentstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'payment_status',
               existing_type=sa.Enum('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', 'FAILED', name='paymentstatus'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
